### ISSUE TITLE
Docker compose instructions to release this wikibase. 

### ISSUE THREAD

**Issue by andrawaag** [ProfessionalWiki/WikibaseEdtf#12]
Is there a docker-compose script to deploy a wikibase with this extension? Like https://github.com/wmde/wikibase-docker/blob/master/docker-compose.yml

**Comment by mzeinstra** [comment]
You mean this one https://github.com/natliblux/saf-wikibase ?

**Comment by JeroenDeDauw** [comment]
The saf-wikibase setup works for the SAF usecase but is specific to it.

Not obvious how to create something generally usable. We could create a version of the wikibase-docker stuff that includes the extension. But doing that for each extension does not seem like a good approach. And it does not solve the case where you want say, both EDTF and LocalMedia.

So perhaps the best approach is to just add the extension to wikibase-docker, or the new release pipeline of WMDE. That likely takes a while though. I've not kicked that process into action yet since we have not properly released the EDTF extension yet. Will do that in the next week(s), still waiting a bit on some last tasks being completed.

**Comment by andrawaag** [comment]
@JeroenDeDauw Currently we rely on the docker-compose script for the modelling of the work (besides WBStack). So yes I would like a pipeline where the EDTF extension is included in the Wikibase-docker compose script. 

When you say that it is not a good approach doing so for each extension, does that mean we will run into issues if both the EDTF and EntitySchema extension are being combined? The Wikibase-docker script now does include the EntitySchema extension.

**Comment by JeroenDeDauw** [comment]
> does that mean we will run into issues if both the EDTF and EntitySchema extension are being combined?

No. You can include all of these extensions together without problems.

**Comment by JeroenDeDauw** [comment]
@andrawaag can't you just use the SAF specific setup linked by Maarten?

**Comment by andrawaag** [comment]
@JeroenDeDauw How do I include the EntitySchema extension here?

**Comment by andrawaag** [comment]
> @andrawaag can't you just use the SAF specific setup linked by Maarten?

We need multiple installs to explore different modelling issues. We currently use wbstack for that, but moving forward we want to include EDTF in this, so we could explore that extension in the modelling as well.

**Comment by mzeinstra** [comment]
Let’s turn this around. How do you currently install wikibase on your own
server. Which repo do you use?

**Comment by mzeinstra** [comment]
@andrawaag

**Comment by andrawaag** [comment]
> Let’s turn this around. How do you currently install wikibase on your own server. Which repo do you use?
> […](#)
https://github.com/wmde/wikibase-docker/blob/master/docker-compose.yml

**Comment by mzeinstra** [comment]
So you want to to know what to add

```
COMPOSER=composer.local.json composer require --no-update professional-wiki/wikibase-edtf:*
composer update professional-wiki/wikibase-edtf --no-dev -o
```

 to a docker-compose.yml that already contains a Wikibase instance?

**Comment by andrawaag** [comment]
Not a wikibase instance, but indeed the script to setup that default wikibase instance.

Currently, all I have to do to deploy a Wikibase is:
1. set up a vm
2. install docker, docker-compose and git
3. wget https://github.com/wmde/wikibase-docker/blob/master/docker-compose.yml 
4. (sudo) docker-compose up

Looking at the diffs between the two repo's it is not completely clear to me, what I need to do to extend either the saf-wikibase to include EntitySchema's or to extend the wikibase-docker script to include the edtf extension.

**Comment by JeroenDeDauw** [comment]
saf-wikibase has EntitySchema

**Comment by mzeinstra** [comment]
Closing this issue since https://github.com/natliblux/saf-wikibase contains what is needed to resolve this ticket.
