### ISSUE TITLE
Adjust for WikibaseClient::getDefaultInstance being removed

### ISSUE THREAD

**Issue by addshore** [ProfessionalWiki/WikibaseEdtf#14]
On master currently you have convenience methods such as this available

https://github.com/wikimedia/Wikibase/blob/21d2c61fe6644719e009bb04f42b768b21de4436/client/includes/WikibaseClient.php#L105-L108

THis should fix the failures @ https://github.com/ProfessionalWiki/WikibaseEdtf/runs/2438392401?check_suite_focus=true

**Comment by JeroenDeDauw** [comment]
Bah. ContainerInterface :( Yay for strings that are not understood by tools

**Comment by addshore** [comment]
> Bah. ContainerInterface :( Yay for strings that are not understood by tools

Hence the static methods ;)
(I guess these could also be done simply with annotations which is what I would expect from laravel etc)

**Comment by JeroenDeDauw** [comment]
Would indeed be cool to get support for WB 37 and add another build to the test matrix https://github.com/ProfessionalWiki/WikibaseEdtf/blob/master/.github/workflows/ci.yml#L17-L22
