### ISSUE TITLE
Entry for EDTF data type in on Special:ListDatatypes

### ISSUE THREAD

**Issue by digitaalwerktuig** [ProfessionalWiki/WikibaseEdtf#26]
This needs to be defined. See:
<img width="332" alt="Schermafbeelding 2022-10-07 om 10 46 38" src="https://user-images.githubusercontent.com/74399885/194512931-15e348b0-e537-4648-a1e9-3f5ead784d79.png">

**Comment by JeroenDeDauw** [comment]
And it was released as 2.0.1 https://github.com/ProfessionalWiki/WikibaseEdtf#version-201---2022-03-26

**Comment by digitaalwerktuig** [comment]
Then I guess Wikibase Cloud is using an older version ;)

**Comment by digitaalwerktuig** [comment]
Already fixed with #21.
