### ISSUE TITLE
Update translations [EDTF 1.2.0]?

### ISSUE THREAD

**Issue by anchardo** [ProfessionalWiki/WikibaseEdtf#33]
Hello,
I have a Wikibase Docker instance with MediaWiki 1.36.3 and the ETDF 1.2.0 extension preinstalled. 
Since then, you have released version 2.0, which contains some new translations/fixes that I'm interested in, but it seems to be designed for MediaWiki 1.37.
--> Is there a way to update the 1.2.0 extension/include the new 'humanized' [translations](https://github.com/ProfessionalWiki/EDTF/tree/master/i18n) I'm interested in?
Since the extension is installed with _Composer_, I don't know how to proceed. Do you have any advice?

Thanks in advance for your help.

**Comment by JeroenDeDauw** [comment]
Version 1.2.0 of Wikibase EDTF specifies that is needs version 2.x or 3.x of the EDTF library. So you should be getting one of those versions via Composer, most likely 3.x.

Relevant code: https://github.com/ProfessionalWiki/WikibaseEdtf/blob/2.1.0/composer.json#L44

**Comment by JeroenDeDauw** [comment]
Ok I see your problem now. You cannot use the latest version due to using an older version of MediaWiki, presumably 1.35. Is that correct? 

There is no way to safely update the EDTF library on the old version of Wikibase Edtf. We could potentially re-add support for MW 35 to the extension.

**Comment by anchardo** [comment]
> You cannot use the latest version due to using an older version of MediaWiki
Yes, exactly. Sorry for the confusion.

> There is no way to safely update the EDTF library on the old version of Wikibase Edtf.
Would it be possible to manually modify some Json myself just for my installation? (I don't know how technically, but that would already be an improvement).

**Comment by JeroenDeDauw** [comment]
That is difficult, and it is likely that the older version of Wikibase Edtf will not work well with the latest versions of the EDTF library. That is why the version restriction exists.

**Comment by anchardo** [comment]
Ok, thank you for the quick answers. So I understand that I should upgrade my Wikibase to version MediaWiki 1.37 to benefit from the last updates unless you decide to re-add support for MW 35 to the extension. 
I'm closing the issue.

**Comment by JeroenDeDauw** [comment]
If you upgrade, you should probably go for MW 39 right away, which is the current Long Term Support release.
