### ISSUE TITLE
What happens when you use the API to set a non-validating EDTF string

### ISSUE THREAD

**Issue by mzeinstra** [ProfessionalWiki/WikibaseEdtf#9]
For the documentation it would be good to know whether the string set not via the GUI will throw an error or will be imported regardless.

How does this currently work?

**Comment by JeroenDeDauw** [comment]
It will throw an error. The GUI uses the API. If you know how to use the browser console, you can open its network tab and then do an edit via the wikibase UI, possibly with an invalid EDTF value, and see the resulting API response.

**Comment by mzeinstra** [comment]
For documentation purposes the API returns this with an invalid date: 

```
{
  "errors": [
    {
      "code": "modification-failed",
      "data": {
        "messages": [
          {
            "name": "wikibase-validator-invalid",
            "parameters": [],
            "html": {
              "*": "Invalid value"
            }
          }
        ]
      },
      "module": "main",
      "*": "Invalid value"
    }
  ],
}
```
